[package]
name = "frdm-server"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "^0.4"
#
#
sal-sync = {git = "https://github.com/a-givertzman/rust-sal-sync.git"}
#
#
linked-hash-map = "^0.5"
indexmap = "^2.5"
hashers = "^1.0"
#
#
serde = { version = "^1.0", features = ["derive"] }
serde_yaml = "^0.9"
serde_json = "^1.0"
#
#
regex = "^1.10"
#
#
strum = "^0.26"
strum_macros = "^0.26"