service Camera Camera1:
    fps: Min                    # Max / Min / 30.0
    resolution: 
        width: 1200
        height: 800
    index: 0
    # address: 192.168.10.12:2020
    pixel-format: BayerBG8      # Mono8/10/12/16, Bayer8/10/12/16, RGB8, BGR8, YCbCr8, YCbCr411, YUV422, YUV411
    exposure:
        auto: Off               # Off / Continuous
        time: 7000              # microseconds
    auto-packet-size: true
    resend-packet: false