TARGET = C_HLTRGB_3_Overlay

OPENCV_INC_PATH = -I/usr/local/include
OPENCV_LIB_PATH = -L/usr/local/lib
OPENCV_LIBS = -lopencv_core -lopencv_features2d -lopencv_imgproc -lopencv_calib3d -lopencv_highgui

include ../common.mk

